### ISSUE TITLE
Різних чисел - мається на увазі що усі однакові елементи повінні бути представленні в одному екземплярі

### ISSUE THREAD

**Issue by Muxamedin** [eTee1/python_lesson#1]
https://github.com/eTee1/python_lesson/blob/fc8f9613a3cce67bd9eb67460754229f5d7e7186/lesson10/task_2.py#L1

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/4419752/185902427-0fb3bd87-f888-4451-970b-04c56ba70207.png">
очікується відповідь - 6 різних елементів 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/4419752/185902531-17ccfb02-e227-4cc5-b013-28daecde2fef.png">

**Comment by eTee1** [comment]
исправил & на ^
